In [1]:
pwd

'C:\\Users\\User\\Documents\\4 year BioEng\\AIHack\\diseases'

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [25]:
admissions_data = pd.read_csv('diseases_all2.csv')

In [26]:
admissions_data.head(11)

,Year,All admissions,All admissions which can be caused by smoking,Cancers which can be caused by smoking,Respiratory diseases which can be caused by smoking,Circulatory diseases which can be caused by smoking,Diseases of the digestive system which can be caused by smoking,Other diseases which can be caused by smoking
0,2008,440400,440400,161200,105800,138600,16500,18300
1,2009,462900,462900,166100,119400,140800,17600,19000
2,2010,461700,461700,166100,116200,141300,18600,19600
3,2011,459900,459900,160300,126200,135400,18100,19900
4,2012,459700,459700,163700,121300,136400,18300,20000
5,2013,460900,460900,156600,131000,134300,18500,20500
6,2014,454700,454700,158800,125600,130800,18400,21100
7,2015,474600,474600,158500,141500,130800,19900,23800
8,2016,474300,474300,159200,142500,129100,20300,23300
9,2017,484700,484700,161100,150800,128400,20100,24300
10,2018,489300,489300,165800,151700,127000,19800,24900

In [27]:
admissions_percentage_data = pd.read_csv('diseases_percentage.csv')

In [28]:
admissions_percentage_data.head(11)

,Year,All admissions,All admissions which can be caused by smoking,Cancers which can be caused by smoking,Respiratory diseases which can be caused by smoking,Circulatory diseases which can be caused by smoking,Diseases of the digestive system which can be caused by smoking,Other diseases which can be caused by smoking
0,2008,4.965070,30.610384,49.976948,51.932831,20.175769,35.232413,10.256203
1,2009,4.903467,31.019598,49.999094,51.440953,20.241764,34.439943,10.489827
2,2010,4.739038,30.917481,50.245747,50.235991,20.375791,34.004371,10.657496
3,2011,4.593138,29.976243,48.958959,48.382746,19.376198,32.091354,10.413672
4,2012,4.522824,29.421484,48.520475,46.794019,19.178209,31.219651,10.209671
5,2013,4.482806,28.801091,48.444440,45.017601,18.749736,30.480975,9.810656
6,2014,4.288515,27.821533,48.077199,43.275902,18.078646,28.200302,9.363946
7,2015,4.309890,27.700443,47.742689,42.039776,17.997342,28.158651,9.623510
8,2016,4.217710,26.833947,46.938148,40.744009,17.309006,26.036854,9.127754
9,2017,4.219549,26.559613,46.849175,39.554698,17.114212,23.808214,9.168284
10,2018,4.226873,26.283242,46.821301,39.150828,16.786265,22.560690,9.049142

In [29]:
frames = [admissions_data,admissions_percentage_data]
df_keys = pd.concat(frames, keys=['Attributable number', 'Attributable percentage'])

In [30]:
df_keys

                            Year  All admissions  \
Attributable number     0   2008   440400.000000
                        1   2009   462900.000000
                        2   2010   461700.000000
                        3   2011   459900.000000
                        4   2012   459700.000000
                        5   2013   460900.000000
                        6   2014   454700.000000
                        7   2015   474600.000000
                        8   2016   474300.000000
                        9   2017   484700.000000
                        10  2018   489300.000000
Attributable percentage 0   2008        4.965070
                        1   2009        4.903467
                        2   2010        4.739038
                        3   2011        4.593138
                        4   2012        4.522824
                        5   2013        4.482806
                        6   2014        4.288515
                        7   2015        4.309890
                        8   2016        4.217710
                        9   2017        4.219549
                        10  2018        4.226873

                            All admissions which can be caused by smoking  \
Attributable number     0                                   440400.000000
                        1                                   462900.000000
                        2                                   461700.000000
                        3                                   459900.000000
                        4                                   459700.000000
                        5                                   460900.000000
                        6                                   454700.000000
                        7                                   474600.000000
                        8                                   474300.000000
                        9                                   484700.000000
                        10                                  489300.000000
Attributable percentage 0                                       30.610384
                        1                                       31.019598
                        2                                       30.917481
                        3                                       29.976243
                        4                                       29.421484
                        5                                       28.801091
                        6                                       27.821533
                        7                                       27.700443
                        8                                       26.833947
                        9                                       26.559613
                        10                                      26.283242

                            Cancers which can be caused by smoking  \
Attributable number     0                            161200.000000
                        1                            166100.000000
                        2                            166100.000000
                        3                            160300.000000
                        4                            163700.000000
                        5                            156600.000000
                        6                            158800.000000
                        7                            158500.000000
                        8                            159200.000000
                        9                            161100.000000
                        10                           165800.000000
Attributable percentage 0                                49.976948
                        1                                49.999094
                        2                                50.245747
                        3                                48.958959
                        4                                48.520475
                        5                                48.444440
                        6                                48.077199
                        7                                47.742689
                        8                                46.938148
                        9                                46.849175
                        10                               46.821301

                            Respiratory diseases which can be caused by smoking  \
Attributable number     0                                       105800.000000
                        1                                       119400.000000
                        2                                       116200.000000
                        3                                       126200.000000
                        4                                       121300.000000
                        5                                       131000.000000
                        6                                       125600.000000
                        7                                       141500.000000
                        8                                       142500.000000
                        9                                       150800.000000
                        10                                      151700.000000
Attributable percentage 0                                           51.932831
                        1                                           51.440953
                        2                                           50.235991
                        3                                           48.382746
                        4                                           46.794019
                        5                                           45.017601
                        6                                           43.275902
                        7                                           42.039776
                        8                                           40.744009
                        9                                           39.554698
                        10                                          39.150828

                            Circulatory diseases which can be caused by smoking  \
Attributable number     0                                       138600.000000
                        1                                       140800.000000
                        2                                       141300.000000
                        3                                       135400.000000
                        4                                       136400.000000
                        5                                       134300.000000
                        6                                       130800.000000
                        7                                       130800.000000
                        8                                       129100.000000
                        9                                       128400.000000
                        10                                      127000.000000
Attributable percentage 0                                           20.175769
                        1                                           20.241764
                        2                                           20.375791
                        3                                           19.376198
                        4                                           19.178209
                        5                                           18.749736
                        6                                           18.078646
                        7                                           17.997342
                        8                                           17.309006
                        9                                           17.114212
                        10                                          16.786265

                            Diseases of the digestive system which can be caused by smoking  \
Attributable number     0                                        16500.000000
                        1                                        17600.000000
                        2                                        18600.000000
                        3                                        18100.000000
                        4                                        18300.000000
                        5                                        18500.000000
                        6                                        18400.000000
                        7                                        19900.000000
                        8                                        20300.000000
                        9                                        20100.000000
                        10                                       19800.000000
Attributable percentage 0                                           35.232413
                        1                                           34.439943
                        2                                           34.004371
                        3                                           32.091354
                        4                                           31.219651
                        5                                           30.480975
                        6                                           28.200302
                        7                                           28.158651
                        8                                           26.036854
                        9                                           23.808214
                        10                                          22.560690

                            Other diseases which can be caused by smoking
Attributable number     0                                    18300.000000
                        1                                    19000.000000
                        2                                    19600.000000
                        3                                    19900.000000
                        4                                    20000.000000
                        5                                    20500.000000
                        6                                    21100.000000
                        7                                    23800.000000
                        8                                    23300.000000
                        9                                    24300.000000
                        10                                   24900.000000
Attributable percentage 0                                       10.256203
                        1                                       10.489827
                        2                                       10.657496
                        3                                       10.413672
                        4                                       10.209671
                        5                                        9.810656
                        6                                        9.363946
                        7                                        9.623510
                        8                                        9.127754
                        9                                        9.168284
                        10                                       9.049142

In [58]:
# Read the cancer related data

xls_cancers_prevalence17 = pd.read_excel('cancerregistrations2017final.xlsx', sheet_name = "Table 1")
xls_cancers_prevalence17.to_csv('cancerregistrations2017final.csv', encoding='utf-8')

for i in range(7):
    xls_cancers_prevalence1 = pd.read_excel('cancerregistrations201' + str(i) + 'final.xls', sheet_name = "Table 1")
    xls_cancers_prevalence1.to_csv('cancerregistrations201' + str(i) + 'final.csv', encoding='utf-8')

NameError: name 'xls_cancers_prevalence1' is not defined

In [ ]:
for i in range(9):
    xls_cancers_prevalence0 = pd.read_excel('cancerregistrations200' + str(i) + 'final.xls', sheet_name = "Table 1")
    xls_cancers_prevalence0.to_csv('cancerregistrations200' + str(i) + 'final.csv', encoding='utf-8')

,Unnamed: 0,Contents,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,Table 1: Registrations of newly diagnosed case...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Registered by December 2017
3,NaN,NaN,NaN,NaN,NaN,Age group,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,ICD-10 code,Site description,NaN,All ages,Under 1,1 to 4,5 to 9,10 to 14,15 to 19,...,45 to 49,50 to 54,55 to 59,60 to 64,65 to 69,70 to 74,75 to 79,80 to 84,85 to 89,90 and over